services:
  setup:
    image: curlimages/curl
    container_name: jf_setup
    depends_on:
      jellyfin:
        condition: service_healthy
    environment:
      JELLYFIN_USER: admin
      JELLYFIN_PASSWORD: admin
    command: >
      sh -c '
        echo "Triggering init..." &&
        curl -s http://jellyfin:8096/Startup/User &&
        echo "Setting up credentials" &&
        curl -s -X POST http://jellyfin:8096/Startup/User -H "Content-Type: application/json" -d "{\"Name\": \"${JELLYFIN_USER}\", \"Password\": \"${JELLYFIN_PASSWORD}\"}" &&
        echo "Completing wizard..." &&
        curl -s -X POST http://jellyfin:8096/Startup/Complete -H "Content-Type: application/json"
        echo "Jellyfin ready!"
      '
  jellyfin:
    image: jellyfin/jellyfin:latest
    container_name: jellyfin
    ports:
      - 8097:8096
    volumes:
      - jf_cache:/cache
      - jf_config:/config
      - jf_media:/media
      - jf_media:/media2
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8096/System/Info/Public"]
      interval: 2s
      timeout: 5s
      retries: 5
    restart: unless-stopped

volumes:
  jf_cache:
  jf_config:
  jf_media:
